<!DOCTYPE html>
<html>
<head>
    <title>BookShop</title>
</head>
<body>
<h1>Создать новый товар</h1>
<form action="/creation" method="post">
    Название объявления: <input type="text" name="title"/><br><br>
    Описание объявления: <input type="text" name="description"/><br><br>
    Цена: <input type="number" name="price"/><br><br>
    <input type="submit" value="Добавить товар"/>
</form>
</body>
</html>
